# Generated by Django 5.0.2 on 2024-03-12 05:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_petdetails_donations'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.CharField(max_length=400)),
                ('date', models.DateField()),
                ('payment', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.petdetails')),
            ],
        ),
    ]
