# Generated by Django 5.0.2 on 2024-03-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_adoptiondetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptiondetails',
            name='aadhar',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='adoptiondetails',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
