# Generated by Django 5.0.2 on 2024-03-22 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_adoptiondetails_aadhar_adoptiondetails_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptiondetails',
            name='aadhar',
        ),
        migrations.RemoveField(
            model_name='adoptiondetails',
            name='age',
        ),
    ]
