# Generated by Django 5.0.2 on 2024-03-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_adoptiondetails_aadhar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petdetails',
            name='is_adopted',
            field=models.BooleanField(default=False),
        ),
    ]
